// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SmartSchedule.Core.Entities;
using SmartSchedule.Core.Entities.Abstractions;
namespace SmartSchedule.Core.Entities;
/// <summary>
/// Представляет здание, содержащее кабинеты и основную информацию, такую как название и адрес.
/// </summary>

public class Building : BaseEntity<int>
{
    /// <summary>
    /// Название здания.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Адрес здания.
    /// </summary>
    public string Address { get; set; } = string.Empty;

    /// <summary>
    /// Список кабинетов, находящихся в здании.
    /// </summary>
    public List<Cabinet> Cabinets { get; set; } = new();
}
