// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SmartSchedule.Core.Entities.Abstractions;

namespace SmartSchedule.Core.Entities;

/// <summary>
/// Представляет кабинет в учебном заведении.
/// </summary>
public class Cabinet : BaseEntity<int>
{
    /// <summary>
    /// Номер кабинета.
    /// </summary>
    /// <example>105</example>
    public string Number { get; set; }

    /// <summary>
    /// Название или номер здания, в котором находится кабинет.
    /// </summary>
    /// <example>Главный корпус</example>
    public int  BuildingId { get; set; }

    /// <summary>
    /// Вместимость кабинета (максимальное количество человек, которое может вместить кабинет).
    /// Может быть null, если вместимость не указана.
    /// </summary>
    /// <example>30</example>
    public int? Capacity { get; set; }

    /// <summary>
    /// Перечень оборудования, доступного в кабинете.
    /// </summary>
    /// <example>Проектор, интерактивная доска, компьютеры</example>
    public string Equipment { get; set; }

    /// <summary>
    /// Список занятий, которые проводятся в этом кабинете.
    /// Инициализируется пустым списком по умолчанию.
    /// </summary>
    public List<Lesson> Lessons { get; set; } = new();
    /// <summary>
    ///  список строений 
    /// </summary>
    public Building Building { get; set; }
}