// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SmartSchedule.Core.Entities.Abstractions;
using System;
using System.Collections.Generic;

namespace SmartSchedule.Core.Entities;
/// <summary>
/// Представляет учебную группу в системе.
/// </summary>
public partial class Group : BaseEntity<int>
{
    /// <summary>
    /// Название группы.
    /// </summary>
    /// <example>22-ПРО-2</example>
    public string Name { get; set; }

    /// <summary>
    /// Коллекция занятий, связанных с этой группой.
    /// Содержит список объектов типа <see cref="Lesson"/>.
    /// Инициализируется пустым списком по умолчанию.
    /// </summary>
    public virtual List<Lesson> Lessons { get; set; } = new();
}