// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SmartSchedule.Core.Entities.Abstractions;
using System;
using System.Collections.Generic;

namespace SmartSchedule.Core.Entities;
/// <summary>
/// Представляет занятие (урок) в расписании.
/// Содержит информацию о предмете, преподавателе, группе, аудитории, времени и дне недели.
/// </summary>
public class Lesson : BaseEntity<int>
{
    /// <summary>
    /// Идентификатор аудитории, в которой проводится занятие.
    /// Может быть null, если аудитория не указана.
    /// </summary>
    public int? CabinetId { get; set; }

    /// <summary>
    /// Идентификатор преподавателя, который проводит занятие.
    /// Может быть null, если преподаватель не указан.
    /// </summary>
    public int? TeacherId { get; set; }

    /// <summary>
    /// Идентификатор группы, для которой проводится занятие.
    /// Может быть null, если группа не указана.
    /// </summary>
    public int? GroupId { get; set; }

    /// <summary>
    /// Идентификатор учебной дисциплины (предмета), которая изучается на занятии.
    /// Может быть null, если предмет не указан.
    /// </summary>
    public int? SubjectId { get; set; }

    /// <summary>
    /// Идентификатор временного слота, в рамках которого проходит занятие.
    /// Может быть null, если временной слот не указан.
    /// </summary>
    public int? TimeSlotId { get; set; }

    /// <summary>
    /// Идентификатор типа недели, к которому относится занятие.
    /// Может быть null, если тип недели не указан.
    /// </summary>
    public int? WeekTypeId { get; set; }

    /// <summary>
    /// Номер подгруппы (например, 1 или 2). 
    /// Если null, значит занятие проводится для всей группы целиком.
    /// </summary>
    public int? Subgroup { get; set; }

    /// <summary>
    /// День недели, в который проводится занятие (например: 1 - Понедельник, 5 - Пятница).
    /// </summary>
    /// <example>1</example>
    public int DayOfWeekId { get; set; }

    /// <summary>
    /// Навигационное свойство: аудитория, в которой проводится занятие.
    /// </summary>
    public virtual Cabinet Cabinet { get; set; }

    /// <summary>
    /// Навигационное свойство: группа, для которой проводится занятие.
    /// </summary>
    public virtual Group Group { get; set; }

    /// <summary>
    /// Навигационное свойство: учебная дисциплина (предмет), которая изучается на занятии.
    /// </summary>
    public virtual Subject Subject { get; set; }

    /// <summary>
    /// Навигационное свойство: преподаватель, проводящий занятие.
    /// </summary>
    public virtual Teacher Teacher { get; set; }

    /// <summary>
    /// Навигационное свойство: временной слот, в котором проводится занятие.
    /// </summary>
    public virtual TimeSlot TimeSlot { get; set; }

    /// <summary>
    /// Навигационное свойство: тип недели, к которому относится занятие.
    /// </summary>
    public virtual WeekType WeekType { get; set; }
    /// <summary>
    /// Навигационное свойство: День недели, к которому относится занятие.
    /// </summary>
    public virtual WeekDay WeekDay { get; set; }
   
}