// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SmartSchedule.Core.Entities.Abstractions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SmartSchedule.Core.Entities;
#nullable disable
/// <summary>
/// Представляет должность преподавателя.
/// </summary>
public class Position : BaseEntity<int>
{
    /// <summary>
    /// Название должности.
    /// </summary>
    /// <example>Профессор</example>
    public string Name { get; set; }

    /// <summary>
    /// Описание должности (необязательное поле).
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Список преподавателей, занимающих эту должность.
    /// </summary>
    public List<Teacher> Teachers { get; set; }= new List<Teacher>();
}

