// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SmartSchedule.Core.Entities.Abstractions;
using System;
using System.Collections.Generic;

namespace SmartSchedule.Core.Entities;

/// <summary>
/// Представляет учебную дисциплину (предмет) в системе.
/// </summary>
public class Subject : BaseEntity<int>
{
    /// <summary>
    /// Название дисциплины.
    /// </summary>
    /// <example>Математический анализ</example>
    public string Title { get; set; }

    /// <summary>
    /// Список занятий, связанных с данной дисциплиной.
    /// Инициализируется пустым списком по умолчанию.
    /// </summary>
    public List<Lesson> Lessons { get; set; } = new();
}