// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SmartSchedule.Core.Entities.Abstractions;
using System;
using System.Collections.Generic;

namespace SmartSchedule.Core.Entities;

/// <summary>
/// Представляет преподавателя в учебной системе.
/// </summary>
public class Teacher : BaseEntity<int>
{
    /// <summary>
    /// Имя преподавателя.
    /// </summary>
    /// <example>Иван</example>
    public string FirstName { get; set; }

    /// <summary>
    /// Отчество преподавателя.
    /// </summary>
    /// <example>Иванович</example>
    public string MiddleName { get; set; }

    /// <summary>
    /// Фамилия преподавателя.
    /// </summary>
    /// <example>Иванов</example>
    public string LastName { get; set; }

    /// <summary>
    /// Список занятий, проводимых данным преподавателем.
    /// Инициализируется пустым списком по умолчанию.
    /// </summary>
    public List<Lesson> Lessons { get; set; } = new();
   

}