// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SmartSchedule.Core.Entities.Abstractions;
using System;
using System.Collections.Generic;

namespace SmartSchedule.Core.Entities;
/// <summary>
/// Представляет временной слот — конкретный временной интервал, в который могут проводиться занятия.
/// Например: 1 пара — с 08:30 до 10:00, 2 пара — с 10:10 до 11:40 и т.д.
/// </summary>
public partial class TimeSlot : BaseEntity<int>
{
    /// <summary>
    /// Номер временного слота (например, порядковый номер пары в расписании).
    /// </summary>
    /// <example>1</example>
    public int SlotNumber { get; set; }

    /// <summary>
    /// Время начала занятия в рамках этого слота.
    /// </summary>
    /// <example>08:30</example>
    public TimeOnly StartTime { get; set; }

    /// <summary>
    /// Время окончания занятия в рамках этого слота.
    /// </summary>
    /// <example>10:00</example>
    public TimeOnly EndTime { get; set; }

    /// <summary>
    /// Список занятий, запланированных в этом временном слоте.
    /// Используется ICollection для поддержки Entity Framework и возможной ленивой загрузки.
    /// Инициализируется пустым списком по умолчанию.
    /// </summary>
    public virtual List<Lesson> Lessons { get; set; } = new();
}