// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SmartSchedule.Core.Entities.Abstractions;
using System;
using System.Collections.Generic;

namespace SmartSchedule.Core.Entities;
/// <summary>
/// Представляет тип недели в расписании.
/// Используется для разделения занятий на чётные/нечётные недели или другие пользовательские типы недель.
/// </summary>
public partial class WeekType : BaseEntity<int>
{
    /// <summary>
    /// Название типа недели.
    /// Например: "Четная", "Нечетная", "Основная", "Дополнительная" и т.д.
    /// </summary>
    /// <example>Четная</example>
    public string Name { get; set; }

    /// <summary>
    /// Список занятий, связанных с этим типом недели.
    /// Позволяет определить, какие уроки проводятся в рамках данного типа недели.
    /// Инициализируется пустым списком по умолчанию.
    /// </summary>
    public List<Lesson> Lessons { get; set; } = new List<Lesson>();
}