// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SmartSchedule.Core.Entities.Abstractions;
namespace SmartSchedule.Core.Entities
{
    /// <summary>
    /// Представляет день недели.
    /// Используется для определения, в какой день проводится занятие.
    /// </summary>
    public class WeekDay : BaseEntity<int>
    {
        /// <summary>
        /// Название дня недели.
        /// Например: "Понедельник", "Вторник", и т.д.
        /// </summary>
        public string Name { get; set; }=string.Empty;
        /// <summary>
        ///  Навигационная свойство
        /// </summary>
        public List<Lesson> Lessons { get; set; } = new List<Lesson>();
    }
}
