// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchedule.Infrastructure.Data;

#nullable disable

namespace SmartSchedule.Infrastructur.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427194641_DeletePositionEntity")]
    partial class DeletePositionEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartSchedule.Core.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_UniName");

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.Cabinet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int")
                        .HasColumnName("building_id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Equipment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("equipment");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("Number", "BuildingId")
                        .IsUnique()
                        .HasDatabaseName("IX_Cabinets_Number_BuildingId");

                    b.ToTable("Cabinets", (string)null);
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_UniName");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("cabinet_id");

                    b.Property<int>("DayOfWeekId")
                        .HasColumnType("int")
                        .HasColumnName("day_of_week_id");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int?>("Subgroup")
                        .HasColumnType("int")
                        .HasColumnName("subgroup");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<int?>("TimeSlotId")
                        .HasColumnType("int")
                        .HasColumnName("time_slot_id");

                    b.Property<int?>("WeekTypeId")
                        .HasColumnType("int")
                        .HasColumnName("week_type_id");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("DayOfWeekId");

                    b.HasIndex("GroupId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("WeekTypeId");

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("IX_UniTitile");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("middle_name");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "MiddleName", "LastName")
                        .IsUnique()
                        .HasDatabaseName("IX_UniqueTeacher_FullName")
                        .HasFilter("[middle_name] IS NOT NULL");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("int")
                        .HasColumnName("slot_number");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.ToTable("TimeSlots", (string)null);
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.WeekDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("WeekDays", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Понедельник"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Вторник"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Среда"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Четверг"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Пятница"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Суббота"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Воскресенье"
                        });
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.WeekType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("WeekTypes", (string)null);
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.Cabinet", b =>
                {
                    b.HasOne("SmartSchedule.Core.Entities.Building", "Building")
                        .WithMany("Cabinets")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.Lesson", b =>
                {
                    b.HasOne("SmartSchedule.Core.Entities.Cabinet", "Cabinet")
                        .WithMany("Lessons")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK__Lessons__Cabinet__4316F928");

                    b.HasOne("SmartSchedule.Core.Entities.WeekDay", "WeekDay")
                        .WithMany("Lessons")
                        .HasForeignKey("DayOfWeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__Lessons__WeekDay__48C3289E");

                    b.HasOne("SmartSchedule.Core.Entities.Group", "Group")
                        .WithMany("Lessons")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK__Lessons__GroupId__44FF419A");

                    b.HasOne("SmartSchedule.Core.Entities.Subject", "Subject")
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK__Lessons__Subject__45F365D3");

                    b.HasOne("SmartSchedule.Core.Entities.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK__Lessons__Teacher__440B1D61");

                    b.HasOne("SmartSchedule.Core.Entities.TimeSlot", "TimeSlot")
                        .WithMany("Lessons")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK__Lessons__TimeSlo__46E78A0C");

                    b.HasOne("SmartSchedule.Core.Entities.WeekType", "WeekType")
                        .WithMany("Lessons")
                        .HasForeignKey("WeekTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK__Lessons__WeekTyp__47DBAE45");

                    b.Navigation("Cabinet");

                    b.Navigation("Group");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("TimeSlot");

                    b.Navigation("WeekDay");

                    b.Navigation("WeekType");
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.Building", b =>
                {
                    b.Navigation("Cabinets");
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.Cabinet", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.Group", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.Subject", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.Teacher", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.TimeSlot", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.WeekDay", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("SmartSchedule.Core.Entities.WeekType", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
